mysite/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path(r'home/', views.HomeView.as_view(), name="home"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf.urls.i18n import i18n_patterns


urlpatterns = i18n_patterns(
    path(r'admin/', admin.site.urls),
    path(r'', views.TopPageView.as_view(), name='toppage'),
    path(r'blog/', include('blog.urls')),
    path(r'users/', include('users.urls')),
    prefix_default_language=False
)

mysite/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path(r'signin/', views.SigninView.as_view(), name="signin"),
    path(r'signout/', views.SignoutView.as_view(), name="signout"),
    path(r'signup/', views.SignupView.as_view(), name="signup"),
    path(r'welcome/', views.WelcomeView.as_view(), name="welcome"),
    path(r'change_password/', views.ChangePasswordView.as_view(),
         name="change_password"),
    path(r'change_password_done/', views.ChangePasswordDoneView.as_view(),
         name="change_password_done"),
    path(r'password_reset/', views.ResetPasswordView.as_view(),
         name="password_reset"),
    path(r'password_reset_done/', views.ResetPasswordDoneView.as_view(),
         name="password_reset_done"),
    path(r'password_reset_confirm/<uidb64>/<token>/',
         views.ResetPasswordConfirmView.as_view(),
         name="password_reset_confirm"),
    path(r'password_reset_confirm/', views.ResetPasswordConfirmView.as_view(),
         name="password_reset_confirm"),
    path(r'password_reset_complete/',
         views.ResetPasswordCompleteView.as_view(),
         name="password_reset_complete"),
    path(r'profile/<int:pk>', views.ProfileView.as_view(),
         name="profile"),
]

mysite/templates/base.html
{% load static %}

<html lang="ja">

<head>
    <meta charset="utf-8">

    <title>My Site</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    {% include 'navbar.html' %}
    {% block head %}{% endblock %}
</head>

<body>
    <header>
        {% block header %}{% endblock %}
    </header>

    <h1>{% block title %}{% endblock %}</h1>

    {% block contents %}{% endblock %}

    {% block footer %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </script>

    {% block scripts %}{% endblock %}

</body>

</html>

mysite/templates/home.html
{% extends 'base.html' %}

{% block contents %}
<div class="container">
    <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
            <a class="p-2 text-muted" href="#">World</a>
            <a class="p-2 text-muted" href="#">U.S.</a>
            <a class="p-2 text-muted" href="#">Technology</a>
            <a class="p-2 text-muted" href="#">Design</a>
            <a class="p-2 text-muted" href="#">Culture</a>
            <a class="p-2 text-muted" href="#">Business</a>
            <a class="p-2 text-muted" href="#">Politics</a>
            <a class="p-2 text-muted" href="#">Opinion</a>
            <a class="p-2 text-muted" href="#">Science</a>
            <a class="p-2 text-muted" href="#">Health</a>
            <a class="p-2 text-muted" href="#">Style</a>
            <a class="p-2 text-muted" href="#">Travel</a>
        </nav>
    </div>

    <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
            <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
            <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and
                efficiently about what's most interesting in this post's contents.</p>
            <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
        </div>
    </div>

    <div class="row mb-2">
        <div class="col-md-6">
            <div class="card flex-md-row mb-4 box-shadow h-md-250">
                <div class="card-body d-flex flex-column align-items-start">
                    <strong class="d-inline-block mb-2 text-primary">World</strong>
                    <h3 class="mb-0">
                        <a class="text-dark" href="#">Featured post</a>
                    </h3>
                    <div class="mb-1 text-muted">Nov 12</div>
                    <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to
                        additional content.</p>
                    <a href="#">Continue reading</a>
                </div>
                <img class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb"
                    alt="Card image cap">
            </div>
        </div>
        <div class="col-md-6">
            <div class="card flex-md-row mb-4 box-shadow h-md-250">
                <div class="card-body d-flex flex-column align-items-start">
                    <strong class="d-inline-block mb-2 text-success">Design</strong>
                    <h3 class="mb-0">
                        <a class="text-dark" href="#">Post title</a>
                    </h3>
                    <div class="mb-1 text-muted">Nov 11</div>
                    <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to
                        additional content.</p>
                    <a href="#">Continue reading</a>
                </div>
                <img class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb"
                    alt="Card image cap">
            </div>
        </div>
    </div>
</div>

<main role="main" class="container">
    <div class="row">
        <div class="col-md-8 blog-main">
            <h3 class="pb-3 mb-4 font-italic border-bottom">
                From the Firehose
            </h3>

            <div class="blog-post">
                <h2 class="blog-post-title">Sample blog post</h2>
                <p class="blog-post-meta">January 1, 2014 by <a href="#">Mark</a></p>

                <p>This blog post shows a few different types of content that's supported and styled with Bootstrap.
                    Basic typography, images, and code are all supported.</p>
                <hr>
                <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus.
                    Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere
                    consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
                <blockquote>
                    <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare
                        vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                </blockquote>
                <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet
                    fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
                <h2>Heading</h2>
                <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo
                    luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac
                    consectetur ac, vestibulum at eros.</p>
                <h3>Sub-heading</h3>
                <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                <pre><code>Example code block</code></pre>
                <p>Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce
                    dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
                <h3>Sub-heading</h3>
                <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia
                    bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus,
                    tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
                </p>
                <ul>
                    <li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>
                    <li>Donec id elit non mi porta gravida at eget metus.</li>
                    <li>Nulla vitae elit libero, a pharetra augue.</li>
                </ul>
                <p>Donec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue.</p>
                <ol>
                    <li>Vestibulum id ligula porta felis euismod semper.</li>
                    <li>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</li>
                    <li>Maecenas sed diam eget risus varius blandit sit amet non magna.</li>
                </ol>
                <p>Cras mattis consectetur purus sit amet fermentum. Sed posuere consectetur est at lobortis.</p>
            </div><!-- /.blog-post -->

            <div class="blog-post">
                <h2 class="blog-post-title">Another blog post</h2>
                <p class="blog-post-meta">December 23, 2013 by <a href="#">Jacob</a></p>

                <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus.
                    Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere
                    consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
                <blockquote>
                    <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare
                        vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                </blockquote>
                <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet
                    fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
                <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo
                    luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac
                    consectetur ac, vestibulum at eros.</p>
            </div><!-- /.blog-post -->

            <div class="blog-post">
                <h2 class="blog-post-title">New feature</h2>
                <p class="blog-post-meta">December 14, 2013 by <a href="#">Chris</a></p>

                <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia
                    bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus,
                    tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
                </p>
                <ul>
                    <li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>
                    <li>Donec id elit non mi porta gravida at eget metus.</li>
                    <li>Nulla vitae elit libero, a pharetra augue.</li>
                </ul>
                <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet
                    fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
                <p>Donec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue.</p>
            </div><!-- /.blog-post -->

            <nav class="blog-pagination">
                <a class="btn btn-outline-primary" href="#">Older</a>
                <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
            </nav>

        </div><!-- /.blog-main -->

        <aside class="col-md-4 blog-sidebar">
            <div class="p-3 mb-3 bg-light rounded">
                <h4 class="font-italic">About</h4>
                <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus
                    sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
            </div>

            <div class="p-3">
                <h4 class="font-italic">Archives</h4>
                <ol class="list-unstyled mb-0">
                    <li><a href="#">March 2014</a></li>
                    <li><a href="#">February 2014</a></li>
                    <li><a href="#">January 2014</a></li>
                    <li><a href="#">December 2013</a></li>
                    <li><a href="#">November 2013</a></li>
                    <li><a href="#">October 2013</a></li>
                    <li><a href="#">September 2013</a></li>
                    <li><a href="#">August 2013</a></li>
                    <li><a href="#">July 2013</a></li>
                    <li><a href="#">June 2013</a></li>
                    <li><a href="#">May 2013</a></li>
                    <li><a href="#">April 2013</a></li>
                </ol>
            </div>

            <div class="p-3">
                <h4 class="font-italic">Elsewhere</h4>
                <ol class="list-unstyled">
                    <li><a href="#">GitHub</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Facebook</a></li>
                </ol>
            </div>
        </aside><!-- /.blog-sidebar -->

    </div><!-- /.row -->

</main><!-- /.container -->
{% endblock %}

{% block footer %}
<footer class="blog-footer">
    <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a
            href="https://twitter.com/mdo">@mdo</a>.</p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>
{% endblock %}

mysite/templates/navbar.html
{% load i18n %}
{% load i18n_switcher %}

<nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="{% url 'toppage' %}">MySite</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-sm-0">
            {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:home' %}">{% trans 'Home' %} <span class="sr-only">(current)</span></a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="#">{% trans 'Link' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">{% trans 'Disabled' %}</a>
            </li>
        </ul>
        <ul class="navbar-nav my-2 my-sm-0" style="margin-right: 20px;">
            {% if request.LANGUAGE_CODE == 'ja' %}
            <a href="{{ request|switch_i18n:'en' }}">English</a>
            {% else %}
            <a href="{{ request|switch_i18n:'ja' }}">日本語</a> 
            {% endif %}
        </ul>
        <ul class="navbar-nav my-2 my-sm-0">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="dropdown-toggle btn btn-outline-info my-2 my-sm-0 " href="#" id="navbarDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa-regular fa-user"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item dropdown-menu-username disabled" tabindex="-1"><small class="text-muted">{{ user.name }}</small></a>
                    <a class="dropdown-item" href="{% url 'users:profile' user.id %}">{% trans 'Profile' %}</a>
                    <a class="dropdown-item" href="{% url 'users:change_password' %}">{% trans 'Change Password' %}</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'users:signout' %}">{% trans 'Sign out' %}</a>
                </div>
            </li>
            {% else %}
            <a class="btn btn-outline-info my-2 my-sm-0" href="{% url 'users:signin' %}">{% trans 'Sign in' %}</a>
            {% endif %}
        </ul>
    </div>
</nav>

mysite/templates/toppage.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block head %}
<style>
    body, html {
        height: 100%;
        margin: 0;
        padding: 0;
        overflow: hidden; /* Ensures no scrolling */
        font-family: 'Inter', 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; /* Modern, clean font */
        background-color: #f8f9fa; /* Very light gray/off-white base */
    }

    .hero-section {
        height: 100vh;
        background-color: #ffffff; /* Pure white background for the hero */
        position: relative;
        overflow: hidden;
    }

    .hero-overlay {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        /* Subtle, very light green tint for the overlay */
        background: linear-gradient(135deg, rgba(144, 238, 144, 0.1) 0%, rgba(60, 179, 113, 0.1) 100%);
        z-index: 1;
    }

    .hero-content {
        position: relative;
        z-index: 2;
        height: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
        text-align: center;
        color: #343a40; /* Dark gray for main text on white background */
    }

    .hero-title {
        font-size: 4rem;
        font-weight: 700;
        color: #212529; /* Even darker for the main title */
        text-shadow: none; /* No shadow for a cleaner look */
        margin-bottom: 1.5rem;
        animation: fadeInUp 1s ease-out;
    }

    .hero-subtitle {
        font-size: 1.5rem;
        color: #6c757d; /* Muted gray for subtitle */
        margin-bottom: 2.5rem;
        animation: fadeInUp 1s ease-out 0.3s both;
    }

    .btn-hero {
        padding: 15px 40px;
        font-size: 1.2rem;
        font-weight: 600;
        border-radius: 50px;
        text-transform: uppercase;
        letter-spacing: 1px;
        transition: all 0.3s ease;
        animation: fadeInUp 1s ease-out 0.6s both;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
        border: none; /* No default button border */
    }

    /* Primary "Join Us Now" button - Vibrant Green */
    .btn-hero.btn-primary-green {
        background-color: #28a745; /* Bootstrap's success green - vibrant */
        color: white; /* White text for contrast */
    }

    .btn-hero.btn-primary-green:hover {
        background-color: #218838; /* Darker green on hover */
        transform: translateY(-3px);
        box-shadow: 0 8px 20px rgba(0, 0, 0, 0.2);
    }

    /* Outline button for "Learn More" - Subtle Green Outline */
    .btn-hero.btn-outline-green {
        background-color: transparent;
        border: 2px solid #28a745; /* Green outline */
        color: #28a745; /* Green text */
    }

    .btn-hero.btn-outline-green:hover {
        background-color: #28a745; /* Solid green on hover */
        color: white; /* White text on hover */
        transform: translateY(-3px);
        box-shadow: 0 8px 20px rgba(0, 0, 0, 0.2);
    }

    .floating-shapes {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 0;
    }

    .shape {
        position: absolute;
        /* Very light green shapes, almost transparent */
        background: rgba(40, 167, 69, 0.05); /* Very subtle green tint */
        border-radius: 50%;
        animation: float 6s ease-in-out infinite;
    }

    /* Shape sizes and positions for subtle background visual */
    .shape-1 {
        width: 100px;
        height: 100px;
        top: 10%;
        left: 5%;
        animation-delay: 0s;
    }

    .shape-2 {
        width: 70px;
        height: 70px;
        top: 70%;
        right: 8%;
        animation-delay: 2s;
    }

    .shape-3 {
        width: 120px;
        height: 120px;
        bottom: 10%;
        left: 15%;
        animation-delay: 4s;
    }

    .shape-4 {
        width: 80px;
        height: 80px;
        top: 25%;
        right: 25%;
        animation-delay: 1s;
    }

    @keyframes float {
        0%, 100% { transform: translateY(0px) rotate(0deg); }
        50% { transform: translateY(-10px) rotate(90deg); } /* Even gentler float */
    }

    @keyframes fadeInUp {
        from {
            opacity: 0;
            transform: translateY(20px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }

    /* Navbar - mostly white with green branding */
    .navbar-custom {
        background: rgba(255, 255, 255, 0.95); /* Mostly white with slight transparency */
        backdrop-filter: blur(8px);
        border-bottom: 1px solid rgba(0, 0, 0, 0.05); /* Very light gray border */
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05); /* Subtle shadow for lift */
    }

    .navbar-brand {
        font-size: 1.8rem;
        font-weight: 700;
        color: #28a745 !important; /* Green brand text */
    }

    .nav-link {
        color: #495057 !important; /* Dark gray for nav links */
        font-weight: 500;
        transition: all 0.3s ease;
    }

    .nav-link:hover {
        color: #28a745 !important; /* Green on hover */
        transform: translateY(-1px);
    }

    @media (max-width: 768px) {
        .hero-title {
            font-size: 2.5rem;
        }

        .hero-subtitle {
            font-size: 1.2rem;
        }

        .btn-hero {
            padding: 12px 30px;
            font-size: 1rem;
        }

        .shape {
            display: none;
        }
    }
</style>
{% endblock %}

{% block contents %}
<nav class="navbar navbar-expand-lg navbar-custom fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'toppage' %}">
            <i class="fas fa-seedling me-2"></i>GreenPoint
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#home">{% trans 'Home' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#about">{% trans 'About' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#services">{% trans 'Services' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#contact">{% trans 'Contact' %}</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:signout' %}">{% trans 'Logout' %}</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:signin' %}">{% trans 'Login' %}</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="hero-section" id="home">
    <div class="floating-shapes">
        <div class="shape shape-1"></div>
        <div class="shape shape-2"></div>
        <div class="shape shape-3"></div>
        <div class="shape shape-4"></div>
    </div>

    <div class="hero-overlay"></div>

    <div class="hero-content">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="hero-title">{% trans 'Innovative Solutions' %}</h1>
                    <p class="hero-subtitle">{% trans 'Join our community to connect, grow, and innovate with purpose.' %}</p>
                    <div class="d-flex flex-column flex-sm-row gap-3 justify-content-center">
                        <a href="{% url 'users:signup' %}" class="btn btn-primary-green btn-hero">
                            <i class="fas fa-handshake me-2"></i>{% trans 'Join Us Now' %}
                        </a>
                        <a href="#about" class="btn btn-outline-green btn-hero">
                            <i class="fas fa-lightbulb me-2"></i>{% trans 'Learn More' %}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    // Prevent scrolling
    document.body.style.overflow = 'hidden';

    // Smooth scroll for anchor links (if needed)
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function (e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({
                    behavior: 'smooth',
                    block: 'start'
                });
            }
        });
    });

    // Add some interactive effects for floating shapes
    document.addEventListener('mousemove', function(e) {
        const shapes = document.querySelectorAll('.shape');
        const x = e.clientX / window.innerWidth;
        const y = e.clientY / window.innerHeight;

        shapes.forEach((shape, index) => {
            const speed = (index + 1) * 0.2; /* Even slower, more subtle movement */
            const xOffset = (x - 0.5) * speed * 10; /* Reduced movement range */
            const yOffset = (y - 0.5) * speed * 10;

            shape.style.transform = `translate(${xOffset}px, ${yOffset}px)`;
        });
    });
</script>
{% endblock %}