mysite/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path(r'home/', views.HomeView.as_view(), name="home"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf.urls.i18n import i18n_patterns


urlpatterns = i18n_patterns(
    path(r'admin/', admin.site.urls),
    path(r'', views.TopPageView.as_view(), name='toppage'),
    path(r'blog/', include('blog.urls')),
    path(r'users/', include('users.urls')),
    prefix_default_language=False
)

mysite/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path(r'signin/', views.SigninView.as_view(), name="signin"),
    path(r'signout/', views.SignoutView.as_view(), name="signout"),
    path(r'signup/', views.SignupView.as_view(), name="signup"),
    path(r'welcome/', views.WelcomeView.as_view(), name="welcome"),
    path(r'change_password/', views.ChangePasswordView.as_view(),
         name="change_password"),
    path(r'change_password_done/', views.ChangePasswordDoneView.as_view(),
         name="change_password_done"),
    path(r'password_reset/', views.ResetPasswordView.as_view(),
         name="password_reset"),
    path(r'password_reset_done/', views.ResetPasswordDoneView.as_view(),
         name="password_reset_done"),
    path(r'password_reset_confirm/<uidb64>/<token>/',
         views.ResetPasswordConfirmView.as_view(),
         name="password_reset_confirm"),
    path(r'password_reset_confirm/', views.ResetPasswordConfirmView.as_view(),
         name="password_reset_confirm"),
    path(r'password_reset_complete/',
         views.ResetPasswordCompleteView.as_view(),
         name="password_reset_complete"),
    path(r'profile/<int:pk>', views.ProfileView.as_view(),
         name="profile"),
]

mysite/users/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def create_user(self, email, name, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            name=name,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):

    class Meta:
        verbose_name = _("User")

    email = models.EmailField(
        verbose_name=_('email address'),
        max_length=255,
        unique=True,
        help_text=_("We'll never share your email with anyone else.")
    )
    name = models.CharField(
        verbose_name=_('Name'),
        max_length=150,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.")
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    def get_absolute_url(self):
        return reverse('users:profile', kwargs={'pk': self.pk})

mysite/users/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm)

from .admin import UserCreationForm, UserChangeForm
from .models import User
from utilities.forms import BootstrapMixin


class SigninForm(BootstrapMixin, AuthenticationForm):
    pass


class SignupForm(BootstrapMixin, UserCreationForm):
    pass


class ChangePasswordForm(BootstrapMixin, PasswordChangeForm):
    pass


class ResetPasswordForm(BootstrapMixin, PasswordResetForm):
    pass


class PasswordSetForm(BootstrapMixin, SetPasswordForm):
    pass


class ProfileForm(BootstrapMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'name')

mysite/users/views.py
from django.urls import reverse_lazy
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeDoneView, PasswordChangeView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView)
from django.views.generic import CreateView, TemplateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.utils.translation import gettext as _

from utilities.mixins import LogoutRequiredMixin, VerifyUserIdentityMixin
from .models import User
from .forms import (SigninForm, SignupForm, ChangePasswordForm,
                    ResetPasswordForm, PasswordSetForm, ProfileForm)


class SigninView(LoginView):
    template_name = 'signin.html'
    form_class = SigninForm
    redirect_authenticated_user = True


class SignoutView(LogoutView):
    pass


class SignupView(LogoutRequiredMixin, CreateView):
    template_name = 'signup.html'
    model = User
    form_class = SignupForm
    success_url = reverse_lazy('users:welcome')

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password1")
        user = authenticate(username=username, password=password)
        if user:
            login(self.request, user)
        return response


class WelcomeView(LoginRequiredMixin, TemplateView):
    template_name = 'welcome.html'


class ChangePasswordView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'password_change.html'
    form_class = ChangePasswordForm
    success_url = reverse_lazy('users:change_password_done')


class ChangePasswordDoneView(LoginRequiredMixin, PasswordChangeDoneView):
    template_name = 'password_change_done.html'


class ResetPasswordView(PasswordResetView):
    template_name = "password_reset_form.html"
    email_template_name = 'password_reset_email.html'
    form_class = ResetPasswordForm
    success_url = reverse_lazy("users:password_reset_done")


class ResetPasswordDoneView(PasswordResetDoneView):
    template_name = "password_reset_done.html"


class ResetPasswordConfirmView(PasswordResetConfirmView):
    template_name = "password_reset_confirm.html"
    form_class = PasswordSetForm
    success_url = reverse_lazy("users:password_reset_complete")


class ResetPasswordCompleteView(PasswordResetCompleteView):
    template_name = "password_reset_complete.html"


class ProfileView(LoginRequiredMixin, VerifyUserIdentityMixin, UpdateView):
    model = User
    form_class = ProfileForm
    template_name = 'profile.html'

    def form_valid(self, form):
        messages.success(self.request, _("Changes successfully saved."))
        return super().form_valid(form)

mysite/users/templates/password_change.html
{% extends 'user_base.html' %}
{% load form_helpers %}
{% load i18n %}

{% block index %}{% trans "Password Change" %}{% endblock %}

{% block detail %}
{% render_errors form %}

<form action="{% url 'users:change_password' %}" method="post">
    {% csrf_token %}
    {% render_field form.old_password %}
    {% render_field form.new_password1 %}
    {% render_field form.new_password2 %}
    {% trans 'Change' as change %}
    {% render_submit_button change %}
</form>
{% endblock %}

mysite/users/templates/password_change_done.html
{% extends 'user_base.html' %}
{% load i18n %}

{% block index %}{% trans "Successfully changed password!" %}{% endblock %}

{% block detail %}
<div class="d-grid gap-2 col-8 mx-auto">
    <a class="btn btn-info btn-lg btn-block" href="{% url 'home' %}">{% trans "Home" %}</a>
</div>
{% endblock %}

mysite/users/templates/password_reset_complete.html
{% extends 'user_base.html' %}
{% load i18n %}

{% block index %}{% trans "Password reset completed!" %}{% endblock %}

{% block detail %}
<p>{% trans "You can sign in with your newly set password." %}</p>
<div class="d-grid gap-2 col-8 mx-auto" style="margin-top: 15px;">
    <a class="btn btn-info btn-lg btn-block" href="{% url 'users:signin' %}">{% trans "Sign in" %}</a>
</div>
{% endblock %}

mysite/users/templates/password_reset_confirm.html
{% extends 'user_base.html' %}
{% load form_helpers %}
{% load i18n %}

{% block index %}{% trans "Password reset" %}{% endblock %}

{% block detail %}
    {% render_errors form %}

    {% if validlink %}
    <form novalidate method="post">
        {% csrf_token %}
        {% render_field form.new_password1 %}
        {% render_field form.new_password2 %}
        {% trans 'Reset' as reset %}
        {% render_submit_button reset %}
    </form>
    {% else %}
    <div class="alert alert-danger" role="alert">
        {% trans "It appears you clicked on an invalid password reset link. Please try again." %}
    </div>
    <div class="d-grid gap-2 col-8 mx-auto">
        <a class="btn btn-info btn-lg btn-block" href="{% url 'users:signin' %}">{% trans "Sign in" %}</a>
    </div>
    {% endif %}
{% endblock %}

mysite/users/templates/password_reset_done.html
{% extends 'user_base.html' %}
{% load i18n %}

{% block index %}{% trans "Password reset sent!" %}{% endblock %}

{% block detail %}
<p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>
<p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>
{% endblock %}

mysite/users/templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

mysite/users/templates/password_reset_form.html
{% extends 'user_base.html' %}
{% load form_helpers %}
{% load i18n %}

{% block index %}{% trans 'Password reset' %}{% endblock %}

{% block detail %}
<p>{% trans 'Forgotten your password?' %}<br>{% trans "Enter your email address below, and we'll email instructions for setting a new one." %}</p>

{% render_errors form %}

<form action="{% url 'users:password_reset' %}" method="post">
    {% csrf_token %}
    {% render_field form.email %}
    {% trans 'Send mail' as sendmail %}
    {% render_submit_button sendmail %}
</form>
{% endblock %}

mysite/users/templates/profile.html
{% extends 'user_base.html' %}
{% load form_helpers %}
{% load i18n %}

{% block index %}{% trans "Profile" %}{% endblock %}

{% block detail %}
{% render_messages %}
{% render_errors form %}

<form action="{% url 'users:profile' user.id %}" method="post">
    {% csrf_token %}
    {% render_field form.email %}
    {% render_field form.name %}
    {% trans 'Save changes' as save_changes %}
    {% render_submit_button save_changes %}
</form>
{% endblock %}

mysite/users/templates/signin.html
{% extends 'user_base.html' %}
{% load form_helpers %}
{% load i18n %}

{% block index %}{% trans "Sign in" %}{% endblock %}

{% block detail %}
{% render_errors form %}

<form action="{% url 'users:signin' %}" method="post">
    {% csrf_token %}
    {% render_field form.username %}
    {% render_field form.password %}
    <div class="text-right" style="margin-bottom: 15px;">
        <a href="{% url 'users:password_reset' %}" style="font-size: 12px;">{% trans 'forget password?' %}</a>
    </div>
    {% trans 'Sign in' as signin %}
    {% render_submit_button signin %}
    <div class="text-center" style="margin-top: 15px;">
        <a href="{% url 'users:signup' %}" style="font-size: 15pt;">{% trans 'Create an account' %}</a>
    </div>
</form>
{% endblock %}

mysite/users/templates/signup.html
{% extends 'user_base.html' %}
{% load form_helpers %}
{% load i18n %}

{% block index %}{% trans 'Sign up' %}{% endblock %}

{% block detail %}
{% render_errors form %}

<form action="{% url 'users:signup' %}" method="post">
    {% csrf_token %}
    {% render_field form.email %}
    {% render_field form.name %}
    {% render_field form.password1 %}
    {% render_field form.password2 %}
    {% trans 'Sign up' as signup %}
    {% render_submit_button signup %}
</form>
{% endblock %}

mysite/users/templates/user_base.html
{% extends 'base.html' %}

{% block contents %}
<div class="container-fluid users-max-width">
    <div class="row">
        <div class="col px-0">
            <h3 class="text-center">{% block index %}{% endblock %}</h3>
        </div>
    </div>

    {% block detail %}{% endblock %}
</div>
{% endblock %}

mysite/users/templates/welcome.html
{% extends 'user_base.html' %}
{% load i18n %}

{% block index %}{% trans "Welcome to MySite!" %}{% endblock %}

{% block detail %}
<div class="d-grid gap-2 col-8 mx-auto" style="margin-top: 20px;">
    <a class="btn btn-info btn-lg btn-block" href="{% url 'home' %}">{% trans "Home" %}</a>
</div>
{% endblock %}